### ISSUE TITLE
Homework 4 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw-04-ajinkyadeshmukh#1]
Dear ajinkyadeshmukh -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

Good work, your score is **9.5/10**

---

### Training and Data: `[10 / 10 points]`

- Reasonable choice for regression: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: [Insert feedback here.]

### Multiple linear regression: `[20 / 20 points]`

  - Correct application: `[15 / 15]`
  - Narrative `[5 / 5]`
  - Feedback: [Insert feedback here.]

### Effect of correlated attributes: `[_ / 15 points]`

  - Correct application: `[10 / 10]`
  - Narrative: `[5 / 5]`
  - Feedback: [Insert feedback here.]

### Ridge regression: `[10 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[5 / 5]`
  - Feedback: [Insert feedback here.]

### Lasso regression: `[10 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[5 / 5]`
  - Feedback: [Insert feedback here.]

### Hyperparameter selection: `[15 / 15 points]`

  - Correct application: `[10 / 10]`
  - Narrative: `[5 / 5]`
  - Feedback: [Insert feedback here.]

### Overall: `[15 / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- **Feedback**: I didn't take points away, but you should have all data in a `data/` folder.
- `[2 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- **Feedback**: you need to have spaces where appropriate. 
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[0 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- **Feedback**: everything is under one commit
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [ ] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by ajinkyapdeshmukh10** [comment]
Dear Greg,
Thank you for the feedback, I'll keep in mind the Quality and Quantity of commits for my future commits.
